config/routes.rb
 Rails.application.routes.draw do

# the first part is what they are going to 
# for example localhost:3000/home, localhost:3000/people/new, localhost:3000/animal
# if it says 'to:' that means forward that request to x#y with x being the controller and y being the action (which is kinda like a view)
# but doesn't have to have a view, can just be a function that does something then redirects after 
# a page can accept a post and get request at any url. this is what determines how those requests are handled. 
#
# This is important for creating a RESTful API. 
# If you dont know what that means, then look up what makes an api RESTful. Basically it means that pages accept post/get requests at the same url 
# handles it from there. 
# for example post to animal should add an animal, get at animal should list animals or get a specific one, depending on how you want to do it. 
 


  get '/home', to: 'main#home'
  patch '/dashboard', to: 'people#dashboardSave'
  get '/dashboard', to: 'people#dashboardGet'

  get 'animals/query'
  get 'animals/querySimple'
  get 'animals/querySimpleStatus'
  get 'animals/querySimpleCoor'
  get 'animals/search'
  get '/animals/new'
  get '/animals/profile'
  get '/animals/edit'

  get '/animals', to: 'animals#list'
  post  '/animals',   to: 'animals#newAnimal'
  patch  '/animals/edit',   to: 'animals#editAnimal'
  delete  '/animals/profile',   to: 'animals#destroy'

  get 'intake/new'   
  get 'intake/edit'
  get 'intake/list'
  post 'intake/new', to:'intake#newIntake'
  patch 'intake/edit', to: 'intake#editIntake'
  
  get 'vetting/new'
  get 'vetting/edit'
  get 'vetting/list'
  post 'vetting/new', to:'vetting#newVetting'
  patch 'vetting/edit', to: 'vetting#editVetting'

  get 'foster/new'
  get 'foster/edit'
  get 'foster/list'
  post 'foster/new', to:'foster#newFoster'
  patch 'foster/edit', to: 'foster#editFoster'

  get 'training/new'
  get 'training/edit'
  get 'training/list'
  post 'training/new', to:'training#newTraining'
  patch 'training/edit', to: 'training#editTraining'

  get 'other/new'
  get 'other/edit'
  get 'other/list'
  post 'other/new', to: 'other#newOther'
  patch 'other/edit', to: 'other#editOther'

  get 'animal_application/new'
  get 'animal_application/edit'
  post 'animal_application/new', to: 'animal_application#newApp'
  patch 'animal_application/edit', to: 'animal_application#editApp'

  get 'adopted/new'
  get 'adopted/edit'
  get 'adopted/list'
  post 'adopted/new', to: 'adopted#newAdopted'
  patch 'adopted/edit', to: 'adopted#editAdopted'

  get 'alerts/new'
  get 'alerts/edit'
  get 'alerts/list'
  get 'alerts/completed'
  get 'alerts/query'
  get '/alerts', to: "alerts#list"
  post  '/alerts',   to: 'alerts#newAlert'
  patch  '/alerts',   to: 'alerts#editAlert'
  delete  '/alerts',   to: 'alerts#deleteAlert'
  post  '/alerts/unsubscribeAlert'

  get '/people', to: "people#list"
  get 'people/new'
  get 'people/edit'
  get 'people/query'
  get 'people/profile'


  post '/people', to: 'people#addEmployee'
  patch '/people', to: 'people#editEmployee'

  get 'password_resets/new'

  get 'password_resets/edit'



  get 'non_user/profile'
  get 'non_user/edit'
  get 'non_user/new'
  get 'non_user/list'
  post '/non_user', to: 'non_user#newUser'
  patch '/non_user', to: 'non_user#editUser'

  get 'trainer/new'
  get 'trainer/profile'
  get 'trainer/list'
  get 'trainer/edit'
  post '/trainer', to: 'trainer#newTrainer'
  patch '/trainer', to: 'trainer#editTrainer'

  get 'veterinarian/new'
  get 'veterinarian/list'
  get 'veterinarian/edit'
  get 'veterinarian/profile'
  post '/veterinarian', to: 'veterinarian#newVet'
  patch '/veterinarian', to: 'veterinarian#editVet'

  get 'animal_facility/new'
  get 'animal_facility/edit'
  get 'animal_facility/profile'
  post '/animal_facility', to: 'animal_facility#newAnifaci'
  patch '/animal_facility', to: 'animal_facility#editAnifaci'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'


  
  resources :users
  resources :account_activations, only: [:edit]
  resources :alert_completions, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  root 'main#home'
end

app/models/veterinarian.rb
class Veterinarian < ActiveRecord::Base
	self.table_name = "veterinarian"
	validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/veterinarian_controller.rb
class VeterinarianController < ApplicationController
  def profile
    @vet = Veterinarian.find(params["param"])
    
    if @vet.address != nil and @vet.state != nil and @vet.zip_code != nil
      @full_address = @vet.address + " " + @vet.state + " " + @vet.zip_code.to_s
    else
      @full_address = nil
    end
  end
  
  def new
  	@vet = Veterinarian.new()
  end

  def list
  	@allVets = Veterinarian.all
  end

  def edit
  	@vet = Veterinarian.find(params["param"])
  end

  def newVet
  	@vet = Veterinarian.new(vet_params)

    if @vet.save
      flash[:success] = "Added Vet"
      redirect_to :controller => "people", :action => "list", :param => @vet
    else
      render 'new'
    end
  end
  
  def editVet
  	@vet = Veterinarian.find(params["format"])
    
    if @vet.update_attributes(vet_params)
      flash[:success] = "Added Vet"
      redirect_to :controller => "people", :action => "list", :param => @vet
    else
      render 'edit'
    end
  	
  end

  def vet_params
  	params.require(:veterinarian).permit(:name, :address , :city , :state, :zip_code, :email, :phone_number, :person_contact, :comments, :credit_card)
  end
end

app/helpers/veterinarian_helper.rb
module VeterinarianHelper
end

app/views/veterinarian/edit.html.erb
<% provide(:title, 'Edit Vet') %>
<h1>Editing <%= @vet.name%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 edit_vet">
    <%= form_for(@vet, html: { multipart: true },  url: veterinarian_path(@vet)) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control required' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :person_contact, "Person of Contact" %>
      <%= f.text_field :person_contact, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :credit_card , "Credit Card on File" %>
      <%= f.check_box :credit_card, class: 'form-control' %>

      <%= f.label :comments %>
      <%= f.text_field :comments, class: 'form-control' %>

      <%= f.submit "Save Vet Edit", class: "btn btn-primary submit-btn" %>
    <% end %>
    </div>
</div>

<script>

$('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".new_vet")[0]))
            e.preventDefault()
        
})
</script>

app/views/veterinarian/list.html.erb
<% provide(:title, "Vets") %>
<h1> Veterinarians </h1>
<!-- TAB NAV LINKS-->
<ul class="nav nav-tabs">
    <li><a href="#vet" data-toggle="tab">Veterinarians</a></li>
</ul>


<!-- TAB CONTENT -->
<div class="tab-content">
  <!-- VET TAB CONTENT -->
  <div class="tab-pane fade in active" id="vet">
    <table id = "user-table" class="table table-bordered table-inverse table-hover user-table">
      <thead>
        <tr>
          <th class= "col-md-1">#</th>
          <th class= "col-md-1">Name</th>
        </tr>
      </thead>
      <tbody>
        <% @allVets.each_with_index do |a, index| %>
           <tr style = "height: 70px;" >
              <th scope="row"><%= index %></th>

              <td> 
                  <%= link_to a.name,  :controller => "veterinarian", :action => "edit", :param => a, :method => "get" %>

                <% if admin?(current_user) %>
                 <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "veterinarian", :action => "edit", :param => a, :method => "get" %>
                 <% end %>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/veterinarian/new.html.erb
 <% provide(:title, 'New Vet') %>
<h1>Add new veterinarian</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 new_vet">
    <%= form_for(@vet, html: { multipart: true },  url: veterinarian_path(@vet)) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control required' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :person_contact, "Person of Contact" %>
      <%= f.text_field :person_contact, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :credit_card , "Credit Card on File" %>
      <%= f.check_box :credit_card, class: 'form-control' %>

      <%= f.label :comments %>
      <%= f.text_field :comments, class: 'form-control' %>

      <%= f.submit "Add Vet Info", class: "btn btn-primary submit-btn" %>
    <% end %>
    </div>
</div>

<script>

$('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".new_vet")[0]))
            e.preventDefault()
        
})
</script>

app/views/veterinarian/profile.html.erb
<% provide(:title, 'Veterinarian') %>
<h1><%= @vet.name%>
    <% if admin?(current_user)%>
 <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "cursor: pointer; font-size:25px;"></span>'.html_safe,  :controller => "veterinarian", :action => "edit", :param => @vet, :method => "get" %>
 <%end %>
 </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<p> Name: <%= @vet.name%> </p>
    <p> Person of Contact: <%= @vet.person_contact%> </p>
	<p> Email: <%=@vet.email%> </p>
	<p> Address: <%=@full_address%> </p>
    <p> Phone Number: <%= @vet.phone_number%> </p>
    <p> Comments: <%= @vet.comments%> </p>

    <%if @vet.credit_card == false %>
        <p> No Credit Card on File</p> 
    <% else %>
        <p> Credit Card on File </p> 
    <% end %> 

    </div>
</div>