config/routes.rb
 Rails.application.routes.draw do

# the first part is what they are going to 
# for example localhost:3000/home, localhost:3000/people/new, localhost:3000/animal
# if it says 'to:' that means forward that request to x#y with x being the controller and y being the action (which is kinda like a view)
# but doesn't have to have a view, can just be a function that does something then redirects after 
# a page can accept a post and get request at any url. this is what determines how those requests are handled. 
#
# This is important for creating a RESTful API. 
# If you dont know what that means, then look up what makes an api RESTful. Basically it means that pages accept post/get requests at the same url 
# handles it from there. 
# for example post to animal should add an animal, get at animal should list animals or get a specific one, depending on how you want to do it. 
 


  get '/home', to: 'main#home'
  patch '/dashboard', to: 'people#dashboardSave'
  get '/dashboard', to: 'people#dashboardGet'

  get 'animals/query'
  get 'animals/querySimple'
  get 'animals/querySimpleStatus'
  get 'animals/querySimpleCoor'
  get 'animals/search'
  get '/animals/new'
  get '/animals/profile'
  get '/animals/edit'

  get '/animals', to: 'animals#list'
  post  '/animals',   to: 'animals#newAnimal'
  patch  '/animals/edit',   to: 'animals#editAnimal'
  delete  '/animals/profile',   to: 'animals#destroy'

  get 'intake/new'   
  get 'intake/edit'
  get 'intake/list'
  post 'intake/new', to:'intake#newIntake'
  patch 'intake/edit', to: 'intake#editIntake'
  
  get 'vetting/new'
  get 'vetting/edit'
  get 'vetting/list'
  post 'vetting/new', to:'vetting#newVetting'
  patch 'vetting/edit', to: 'vetting#editVetting'

  get 'foster/new'
  get 'foster/edit'
  get 'foster/list'
  post 'foster/new', to:'foster#newFoster'
  patch 'foster/edit', to: 'foster#editFoster'

  get 'training/new'
  get 'training/edit'
  get 'training/list'
  post 'training/new', to:'training#newTraining'
  patch 'training/edit', to: 'training#editTraining'

  get 'other/new'
  get 'other/edit'
  get 'other/list'
  post 'other/new', to: 'other#newOther'
  patch 'other/edit', to: 'other#editOther'

  get 'animal_application/new'
  get 'animal_application/edit'
  post 'animal_application/new', to: 'animal_application#newApp'
  patch 'animal_application/edit', to: 'animal_application#editApp'

  get 'adopted/new'
  get 'adopted/edit'
  get 'adopted/list'
  post 'adopted/new', to: 'adopted#newAdopted'
  patch 'adopted/edit', to: 'adopted#editAdopted'

  get 'alerts/new'
  get 'alerts/edit'
  get 'alerts/list'
  get 'alerts/completed'
  get 'alerts/query'
  get '/alerts', to: "alerts#list"
  post  '/alerts',   to: 'alerts#newAlert'
  patch  '/alerts',   to: 'alerts#editAlert'
  delete  '/alerts',   to: 'alerts#deleteAlert'
  post  '/alerts/unsubscribeAlert'

  get '/people', to: "people#list"
  get 'people/new'
  get 'people/edit'
  get 'people/query'
  get 'people/profile'


  post '/people', to: 'people#addEmployee'
  patch '/people', to: 'people#editEmployee'

  get 'password_resets/new'

  get 'password_resets/edit'



  get 'non_user/profile'
  get 'non_user/edit'
  get 'non_user/new'
  get 'non_user/list'
  post '/non_user', to: 'non_user#newUser'
  patch '/non_user', to: 'non_user#editUser'

  get 'trainer/new'
  get 'trainer/profile'
  get 'trainer/list'
  get 'trainer/edit'
  post '/trainer', to: 'trainer#newTrainer'
  patch '/trainer', to: 'trainer#editTrainer'

  get 'veterinarian/new'
  get 'veterinarian/list'
  get 'veterinarian/edit'
  get 'veterinarian/profile'
  post '/veterinarian', to: 'veterinarian#newVet'
  patch '/veterinarian', to: 'veterinarian#editVet'

  get 'animal_facility/new'
  get 'animal_facility/edit'
  get 'animal_facility/profile'
  post '/animal_facility', to: 'animal_facility#newAnifaci'
  patch '/animal_facility', to: 'animal_facility#editAnifaci'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'


  
  resources :users
  resources :account_activations, only: [:edit]
  resources :alert_completions, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  root 'main#home'
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
   before_filter :check_for_mobile
   skip_before_filter :verify_authenticity_token, :only => :dashboardSave
  # if you are wondering how these get called, look in routes. 

  #for the main people that displays all of them
  def list
   
    @allPeople = User.all.order('name ASC')
    @allNonUser = NonUser.all.order('name ASC')
    @allVets = Veterinarian.all.order('name ASC')
    @allTrainer = Trainer.all.order('name ASC')
    @allAniFaci = AnimalFacility.all.order('name ASC')
    user = User.all.order('name ASC')
  end

  #page for adding new people to the organization 
  def new
  	 @employee = User.new
     @roles = Role.all
     puts "ROLES ARE GOING NOW"
  end

  def edit
    @employee = User.find(params["param"])
    @roles = Role.all
  end
  
   def profile
    @employee = User.find(params["param"])

    if @employee.address != nil and @employee.city != nil and @employee.state != nil and @employee.zip_code != nil
      @full_address = @employee.address.to_s + " " + @employee.city.to_s + " " + @employee.state.to_s + " " + @employee.zip_code.to_s

    else
      @full_address = nil
    end
    @foster_ok = @employee.foster_check
    @adopt_ok = @employee.adopt_check

    @foster = Foster.find_by user_id: @employee.id
    if @foster != nil
      @allFosters = FosterStatus.where(foster_id: @foster.id).order('foster_date DESC')

    end

    @adoptions = Adopter.find_by user_id: @employee.id

    if @adoptions != nil
      @allAdoptions = Adopted.where(adopter_id: @adoptions.id).order('adopt_date DESC')
      @allApps = AnimalApplication.where(adopter_id: @adoptions.id).order('app_date DESC')
 
    end
  end

  def people_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :role_id, :picture, :disabled, :address, :city,
                                   :state, :zip_code, :foster_check, :adopt_check, :comments, :home_comm, :homecheck, :phone_number, :user_document)
  end
  # the code that actually adds an employee. 
  def addEmployee

    @employee = User.new(people_params)

    
    
    if @employee.save
      UserMailer.account_activation(@employee, current_user).deliver_now
      flash[:success] = "Added employee"
      redirect_to people_url
    else
      @roles = Role.all
      render 'new'
    end
  end

def editEmployee
    @employee = User.find(params["format"])

    if @employee.update_attributes(people_params)

      if @employee.foster_check = true
          #if they weren't approved for a foster at first but now are
          @new_foster = Foster.new({non_user_id: nil, user_id: @employee.id,})
          @new_foster.save
      end
      
      if @employee.adopt_check = true
        #if they weren't approved for a adopter at first but now are
        @new_adopter = Adopter.new({non_user_id: nil, user_id: @employee.id,})
        @new_adopter.save
      end 

      flash[:success] = "Saved employee"
      redirect_to people_url
    else
      @roles = Role.all
      render 'edit'
    end
  end
def dashboardSave
    str = params["str"]
    puts str
    if str and  ! str.include? "undefined"
      @employee = User.where("id =  " + current_user.id.to_s).update_all( dashboard: str )
    end
    
    
   

    render json: params

end
def dashboardGet
  json = {"str" => current_user.dashboard}
  render json: json
end

def query
    @users = User.all.limit(10)
    arr = []
    @users.each do |d|
      arr.push({
        "id" =>  d.id, 
        "name" => d.name,
        "email" => d.email,

      })
    end
    render json: arr
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_error_messages.html.erb
<% if @employee.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@employee.errors.count, "error") %>.
    </div>
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/people/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Editing <%= @employee.email%></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 edit_user">
    <!-- form for submitting employees. 
    submits to /people path. that can be found in routes. 
    passes in @employee that is defined by the form
    thats what :name, :email,  etc is for 

  --> 
    <%= form_for(@employee, html: { multipart: true },  url: people_path(@employee)) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control required' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control required' %>

      <%= f.label :comments %>
      <%= f.text_field :comments, class: 'form-control' %>

      <%= f.label :home_comm , "Home Comments"%>
      <%= f.text_area :home_comm, class: 'form-control' %>

      <%= f.label :homecheck %>
      <%= f.check_box :homecheck, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control required' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control required' %>

      <%= f.label :role_id %>
      <%= f.collection_select :role_id, @roles, :id, :title, :prompt => "Select Role" , class: 'form-control required' %>

      
      <% if admin?(current_user) %>

        <%= f.label :foster %>
        <%= f.check_box :foster_check, class: 'form-control' %>

        <%= f.label :adopt %>
        <%= f.check_box :adopt_check, class: 'form-control' %>
        
        <%= f.label :disabled %>
        <%= f.check_box :disabled, class: 'form-control' %>

        <br>
      <% end %>


        <div id="upload-buttons" style="padding-top: 15px">

        <div class = "upload-wrapper">
            <span class="btn btn-large btn-warning btn-file">
                <%= label_tag "Homecheck Document" %>
                <%= f.file_field :user_document, class: 'file-upload' %>
            </span>
            <span class = "file-name">
              <% if @employee.user_document.length > 0 %>
                <%= @employee.user_document.file.filename %> 
              <% end %>
              <span class = "glyphicon glyphicon-remove remove-file" style = "display:none"> </span>
            </span>
            
        </div>
        </div>
      

      <span class="picture">
        <%= f.label :Picture, "Profile Picture" %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit "Submit changes", class: "btn btn-primary submit-btn" %>
    <% end %>
    </div>
</div>

<script>

$('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".edit_user")[0]))
            e.preventDefault()
        
})
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

    $(".file-upload").change(function(input) { 
    var input = input.target;
    if (input.files && input.files[0]) {
        var fileName = input.files[0].name;
        var container =  $(this).closest(".upload-wrapper");
        var nameSpan = container.find(".file-name");
        nameSpan.text(fileName);
        var removeSpan = container.find(".remove-file");
        removeSpan.show();
        }
  }); 

</script>

app/views/people/list.html.erb
<% provide(:title, "People") %>

<div class="bg-page">
  <h2 class= "pg-title">People List</h2>
  <!-- BUTTONS TO ADD USERS -->
  <div class="col-md-offset-10 btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
      Add new User <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
    <% if admin?(current_user) %>
      <li><%= link_to "Add User".html_safe,  :controller => "people", :action => "new", :method => "get" %></li>
      <li><%= link_to "Add Non User".html_safe,  :controller => "non_user", :action => "new", :method => "get" %></li>
      <li><%= link_to "Add Trainer".html_safe,  :controller => "trainer", :action => "new", :method => "get" %></li>
      <li><%= link_to "Add Veterinarian".html_safe,  :controller => "veterinarian", :action => "new", :method => "get" %></li>  
      <li><%= link_to "Add Animal Facility".html_safe,  :controller => "animal_facility", :action => "new", :method => "get" %></li>  
    <% end %>
    </ul>
  </div>

  <!-- TAB NAV LINKS-->
  <div class="tab-head">
    <ul class="nav nav-tabs-unstyled nav-justified">
        <li class="active"><a href="#user" data-toggle="tab">Users</a></li>
        <li><a href="#non_user" data-toggle="tab">Non Users</a></li>
        <li><a href="#trainer" data-toggle="tab">Trainers</a></li>
        <li><a href="#vet" data-toggle="tab">Veterinarian</a></li>
        <li><a href="#animal_fac" data-toggle="tab">Animal Facilities</a></li>
    </ul>
  </div>


  <!-- TAB CONTENT -->
  <div class="tab-content">
    
    <!-- USER TAB CONENT -->
    <div class="tab-pane fade in active" id="user">
      <table id = "people-table" class="table table-bordered table-inverse table-hover people-table">
        <thead>
          <tr>
            <th class= "col-md-1">#</th>
            <th class= "col-md-1">Pic</th>
            <th class= "col-md-3">Name</th>
            <th class= "col-md-3">Role</th>
          </tr>
        </thead>
        <tbody>
          <% @allPeople.each_with_index do |a, index| %>
             <tr style = "height: 70px;" >
                <th scope="row"><%= index %></th>
                <td>
                 <%= display_avatar(a, "50x50") %>

                  </td>

                <td> 
                    <%= link_to a.name,  :controller => "people", :action => "profile", :param => a, :method => "get" %>

                  <% if admin?(current_user) %>
                   <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "people", :action => "edit", :param => a, :method => "get" %>
                   <% end %>
               </td>
                <td> <%= a.role.title %> </td>
                
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- NONUSER TAB CONTENT -->
    <div class="tab-pane fade" id="non_user">
      <table id = "user-table" class="table table-bordered table-inverse table-hover user-table">
        <thead>
          <tr>
            <th class= "col-md-1">#</th>
            <th class= "col-md-1">Pic</th>
            <th class= "col-md-3">Name</th>
          </tr>
        </thead>
        <tbody>
          <% @allNonUser.each_with_index do |a, index| %>
             <tr style = "height: 70px;" >
                <th scope="row"><%= index %></th>
                <td>
                 <%= display_avatar(a, "50x50") %>
                </td>

                <td> 
                    <%= link_to a.name,  :controller => "non_user", :action => "profile", :param => a, :method => "get" %>

                  <% if admin?(current_user) %>
                   <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "non_user", :action => "edit", :param => a, :method => "get" %>
                   <% end %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <!-- TRAINER TAB CONTENT -->
    <div class="tab-pane fade" id="trainer">
      <table id = "user-table" class="table table-bordered table-inverse table-hover user-table">
        <thead>
          <tr>
            <th class= "col-md-1">Name</th>
            <th class= "col-md-2">Person of Contact</th>
            <th class= "col-md-3">Address</th>
            <th class= "col-md-1">Phone Number</th>
          </tr>
        </thead>
        <tbody>
          <% @allTrainer.each_with_index do |a, index| %>
             <tr style = "height: 70px;" >
                <td> 
                    <%= link_to a.name,  :controller => "trainer", :action => "profile", :param => a, :method => "get" %>

                  <% if admin?(current_user) %>
                   <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "trainer", :action => "edit", :param => a, :method => "get" %>
                   <% end %>
                </td>
                <td><%= a.person_contact%></td>
                <td>
                  <% if a.address != nil and a.city != nil and a.state != nil and a.zip_code !=nil%>
                    <%= a.address.to_s + " " + a.city.to_s + " " + a.state.to_s + " " + a.zip_code.to_s%>
                  <% end %>
                </td>
                <td><%= a.phone_number%></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
    <!-- VET TAB CONTENT -->
    <div class="tab-pane fade" id="vet">
      <table id = "user-table" class="table table-bordered table-inverse table-hover user-table">
        <thead>
          <tr>
            <th class= "col-md-3">Name</th>
            <th class= "col-md-2">Person of Contact</th>
            <th class= "col-md-3">Address</th>
            <th class= "col-md-1">Phone Number</th>
          </tr>
        </thead>
        <tbody>
          <% @allVets.each do |a| %>
             <tr style = "height: 70px;" >
                <td> 
                    <%= link_to a.name,  :controller => "veterinarian", :action => "profile", :param => a, :method => "get" %>

                  <% if admin?(current_user) %>
                   <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "veterinarian", :action => "edit", :param => a, :method => "get" %>
                   <% end %>
                </td>
                <td><%= a.person_contact%></td>
                <td>
                  <% if a.address != nil and a.city != nil and a.state != nil and a.zip_code !=nil%>
                    <%= a.address.to_s + " " + a.city.to_s + " " + a.state.to_s + " " + a.zip_code.to_s%>
                  <% end %>
                </td>
                <td><%= a.phone_number%></td>
              </tr>

          <% end %>
        </tbody>
      </table>
    </div>
    <!--- ANIMAL FACILITY-->
    <div class="tab-pane fade" id="animal_fac">
      <table id = "user-table" class="table table-bordered table-inverse table-hover user-table">
        <thead>
          <tr>
            <th class= "col-md-1">Name</th>
            <th class= "col-md-2">Address</th>
            <th class= "col-md-1">Phone Number</th>
          </tr>
        </thead>
        <tbody>
          <% @allAniFaci.each_with_index do |a, index| %>
             <tr style = "height: 70px;">
                <td> 
                    <%= link_to a.name,  :controller => "animal_facility", :action => "profile", :param => a, :method => "get" %>

                  <% if admin?(current_user) %>
                   <%= link_to ' <span class ="glyphicon glyphicon-pencil" style = "display:none; cursor: pointer;"></span>'.html_safe,  :controller => "animal_facility", :action => "edit", :param => a, :method => "get" %>
                   <% end %>
                </td>
                <td>
                  <% if a.address != nil and a.city != nil and a.state != nil and a.zip_code !=nil%>
                    <%= a.address.to_s + " " + a.city.to_s + " " + a.state.to_s + " " + a.zip_code.to_s%>
                  <% end %>
                </td>
                <td><%= a.phone_number%></td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>

$("#people-table tr").hover(
  function(){
    $(this).find(".glyphicon-pencil").show()
  },
  function(){
    $(this).find(".glyphicon-pencil").hide()
  }
)
</script>

<script>
$("#user-table tr").hover(
  function(){
    $(this).find(".glyphicon-pencil").show()
  },
  function(){
    $(this).find(".glyphicon-pencil").hide()
  }
)
</script>

app/views/people/new.html.erb
 <% provide(:title, 'New User') %>
<h1>Add new User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 new_user">
    <!-- form for submitting employees. 
    submits to /people path. that can be found in routes. 
    passes in @employee that is defined by the form
    thats what :name, :email,  etc is for 

  --> 
    <%= form_for(@employee, html: { multipart: true },  url: people_path(@employee)) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control required' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>

      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control required' %>

      <%= f.label :comments %>
      <%= f.text_field :comments, class: 'form-control' %>

      <%= f.label :home_comm , "Home Comments"%>
      <%= f.text_area :home_comm, class: 'form-control' %>

      <%= f.label :homecheck %>
      <%= f.check_box :homecheck, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control required' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control required' %>

      <%= f.label :role_id %>
      <%= f.collection_select :role_id, @roles, :id, :title, :prompt => "Select Role" %>

      <div class = "upload-wrapper" style= "padding-bottom: 15px">
            <span class="btn btn-large btn-warning btn-file">
                <%= label_tag "Homecheck Document" %>
                <%= f.file_field :user_document, class: 'file-upload' %>
            </span>
            <span class = "file-name"></span>
            <span class = "glyphicon glyphicon-remove remove-file" style = "display:none"></span>
        </div>

      <span class="picture">
        <%= f.label :Picture, "Profile Picture" %>
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit "Create my account", class: "btn btn-primary submit-btn" %>
    <% end %>
    </div>
</div>

<script>

$('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".new_user")[0]))
            e.preventDefault()
        
})
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

  $(".file-upload").change(function(input) { 
    var input = input.target;
    if (input.files && input.files[0]) {
        var fileName = input.files[0].name;
        var container =  $(this).closest(".upload-wrapper");
        var nameSpan = container.find(".file-name");
        nameSpan.text(fileName);
        var removeSpan = container.find(".remove-file");
        removeSpan.show();
        }
  }); 

  $(".remove-file").on('click', function(){
        var container =  $(this).closest(".upload-wrapper");

        nameSpan = container.find(".file-name");
        nameSpan.text("");

        var removeSpan = container.find(".remove-file");
        removeSpan.hide();

        var inputfield  = container.find(".file-upload");
        inputfield[0].value = "";

  });
</script>