config/routes.rb
 Rails.application.routes.draw do

# the first part is what they are going to 
# for example localhost:3000/home, localhost:3000/people/new, localhost:3000/animal
# if it says 'to:' that means forward that request to x#y with x being the controller and y being the action (which is kinda like a view)
# but doesn't have to have a view, can just be a function that does something then redirects after 
# a page can accept a post and get request at any url. this is what determines how those requests are handled. 
#
# This is important for creating a RESTful API. 
# If you dont know what that means, then look up what makes an api RESTful. Basically it means that pages accept post/get requests at the same url 
# handles it from there. 
# for example post to animal should add an animal, get at animal should list animals or get a specific one, depending on how you want to do it. 
 


  get '/home', to: 'main#home'
  patch '/dashboard', to: 'people#dashboardSave'
  get '/dashboard', to: 'people#dashboardGet'

  get 'animals/query'
  get 'animals/querySimple'
  get 'animals/querySimpleStatus'
  get 'animals/querySimpleCoor'
  get 'animals/search'
  get '/animals/new'
  get '/animals/profile'
  get '/animals/edit'

  get '/animals', to: 'animals#list'
  post  '/animals',   to: 'animals#newAnimal'
  patch  '/animals/edit',   to: 'animals#editAnimal'
  delete  '/animals/profile',   to: 'animals#destroy'

  get 'intake/new'   
  get 'intake/edit'
  get 'intake/list'
  post 'intake/new', to:'intake#newIntake'
  patch 'intake/edit', to: 'intake#editIntake'
  
  get 'vetting/new'
  get 'vetting/edit'
  get 'vetting/list'
  post 'vetting/new', to:'vetting#newVetting'
  patch 'vetting/edit', to: 'vetting#editVetting'

  get 'foster/new'
  get 'foster/edit'
  get 'foster/list'
  post 'foster/new', to:'foster#newFoster'
  patch 'foster/edit', to: 'foster#editFoster'

  get 'training/new'
  get 'training/edit'
  get 'training/list'
  post 'training/new', to:'training#newTraining'
  patch 'training/edit', to: 'training#editTraining'

  get 'other/new'
  get 'other/edit'
  get 'other/list'
  post 'other/new', to: 'other#newOther'
  patch 'other/edit', to: 'other#editOther'

  get 'animal_application/new'
  get 'animal_application/edit'
  post 'animal_application/new', to: 'animal_application#newApp'
  patch 'animal_application/edit', to: 'animal_application#editApp'

  get 'adopted/new'
  get 'adopted/edit'
  get 'adopted/list'
  post 'adopted/new', to: 'adopted#newAdopted'
  patch 'adopted/edit', to: 'adopted#editAdopted'

  get 'alerts/new'
  get 'alerts/edit'
  get 'alerts/list'
  get 'alerts/completed'
  get 'alerts/query'
  get '/alerts', to: "alerts#list"
  post  '/alerts',   to: 'alerts#newAlert'
  patch  '/alerts',   to: 'alerts#editAlert'
  delete  '/alerts',   to: 'alerts#deleteAlert'
  post  '/alerts/unsubscribeAlert'

  get '/people', to: "people#list"
  get 'people/new'
  get 'people/edit'
  get 'people/query'
  get 'people/profile'


  post '/people', to: 'people#addEmployee'
  patch '/people', to: 'people#editEmployee'

  get 'password_resets/new'

  get 'password_resets/edit'



  get 'non_user/profile'
  get 'non_user/edit'
  get 'non_user/new'
  get 'non_user/list'
  post '/non_user', to: 'non_user#newUser'
  patch '/non_user', to: 'non_user#editUser'

  get 'trainer/new'
  get 'trainer/profile'
  get 'trainer/list'
  get 'trainer/edit'
  post '/trainer', to: 'trainer#newTrainer'
  patch '/trainer', to: 'trainer#editTrainer'

  get 'veterinarian/new'
  get 'veterinarian/list'
  get 'veterinarian/edit'
  get 'veterinarian/profile'
  post '/veterinarian', to: 'veterinarian#newVet'
  patch '/veterinarian', to: 'veterinarian#editVet'

  get 'animal_facility/new'
  get 'animal_facility/edit'
  get 'animal_facility/profile'
  post '/animal_facility', to: 'animal_facility#newAnifaci'
  patch '/animal_facility', to: 'animal_facility#editAnifaci'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'


  
  resources :users
  resources :account_activations, only: [:edit]
  resources :alert_completions, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  root 'main#home'
end

app/models/alert.rb
class Alert < ActiveRecord::Base
    attr_accessor :assigned
	belongs_to :assignee, :class_name => 'User'
	belongs_to :created_by, :class_name => 'User'
    belongs_to :animal, :class_name => 'Animal'
    belongs_to :type, :class_name => 'AlertType'

    validates :title, presence: true
    validates :alert_type_id, presence: true
    #validates :assignee_id, presence: true
    validates :created_by_id, presence: true
     def start_time
        self.date ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end
end

app/models/alert_type.rb
class AlertType < ActiveRecord::Base
	self.table_name = "alert_types"
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_filter :check_for_mobile
  skip_before_filter :verify_authenticity_token, :only => [:deleteAlert, :unsubscribeAlert, :completed]
  layout "login", :only => :completed
  def date_format(date)
    return date.to_formatted_s(:long_ordinal)
  end
  def completed

  end
  #listing all the alerts
  def list
    @allAlerts = []
    @myAlerts = []
    @alertsRaw = UserAlert.where(user_id: current_user.id)
    @createdAlerts = Alert.where(created_by_id: current_user.id)
    puts @alerts

    @alertsRaw.each do |a|
      a.alert.assigned = true
      @myAlerts.push(a.alert)
      @allAlerts.push(a.alert)
    end
    @createdAlerts.each do |a|
      a.assigned = false
      unless (@allAlerts.include?(a))
       @allAlerts.push(a)
     end
    end
  end

  #for the new alerts
  def new
    update_referer(request.referer, request.original_url)
    if(params["param"] != nil) 
      @animal = Animal.where('id = ' + params["param"])
    else
      @animal = []
    end
    @alert = Alert.new
    @types = AlertType.all
    @users = User.where(disabled: false)
    @animals = Animal.all

  end
  def edit
    update_referer(request.referer, request.original_url)
    @alert = Alert.find(params["param"])
    @types = AlertType.all
    @users = User.where(disabled: false)
    @animals = Animal.all
    @assigneesSelected = []
    @animalsSelected = []
    @assigneesRaw = UserAlert.where(alert_id: params["param"])
    @animalsRaw = AnimalAlert.where(alert_id: params["param"])
    @animalsRaw.each do |a|
      @animalsSelected.push(a.animal)
    end
    @assigneesRaw.each do |a|
      @assigneesSelected.push(a.user)
    end

  end
  def unsubscribeAlert


     id = request["param"]
     UserAlert.where("alert_id =" + id.to_s + " and user_id = " + current_user.id.to_s).delete_all
     render json: {"status" => "success"}
    

  end 
  def deleteAlert
    

    id = request["param"]
    AnimalAlert.where("alert_id =" + id.to_s).delete_all
    UserAlert.where("alert_id =" + id.to_s).delete_all
  
    Alert.where("id =" + id.to_s).delete_all

    render json: {"status" => "success"}
  
    
  end
  #for displaying alerts
  def display
    @alert = Alert.find(params["param"])
  end

  def newAlert
    

    @alert = Alert.new(alert_params)  do |q|
          q.created_by_id = current_user.id
    end

    @allAlerts = Alert.all
    @types = AlertType.all
    @users = User.all
    
    if @alert.save
      if params["assignees"]
        arr = params["assignees"].split("|")
        arr.each do |d|
          
        @userAlert = UserAlert.new({alert_id: @alert.id, user_id: d})
        @userAlert.save
        user = User.find(d)
        UserMailer.alert_email_assigned(user, @alert).deliver_now
        @userAlert.update_attributes(email_date: Time.now)
        end
      end
      if params["animals"]
        arr = params["animals"].split("|")
        arr.each do |d|
          
        @animalAlert = AnimalAlert.new({alert_id: @alert.id, animal_id: d})
        @animalAlert.save
        end
      end
      flash.now[:success] = "New Alert!"
      redirect_to session[:prev_url]
    else       
      flash.now[:danger] = "Error adding Alert!"
      render 'new'
    end
  end

  def editAlert
    @alert = Alert.find(params["format"])
    if @alert.update_attributes(alert_params)
      #delete old ones
      UserAlert.where("alert_id = " + @alert.id.to_s).delete_all
      AnimalAlert.where("alert_id = " + @alert.id.to_s).delete_all
      #add new ones
      if params["assignees"]
        arr = params["assignees"].split("|")
        arr.each do |d|
          
        @userAlert = UserAlert.new({alert_id: @alert.id, user_id: d})
        @userAlert.save
        user = User.find(d)
        UserMailer.alert_email_edited(user, @alert).deliver_now
        @userAlert.update_attributes(email_date: Time.now)
        end
      end
      if params["animals"]
        arr = params["animals"].split("|")
        arr.each do |d|
          
        @animalAlert = AnimalAlert.new({alert_id: @alert.id, animal_id: d})
        @animalAlert.save
        end
      end


      flash[:success] = "Updated Alert"
      redirect_to session[:prev_url]

    else
      flash.now[:danger] = "Error creating alert"
      @type = Type.all
      render 'edit'
    end

  end
 
  def alert_params
    params.require(:alert).permit(:title, :description, :date, :alert_type_id, :assignee_id,
                  :created_by_id, :animal_id, :location, :created_at, :required)
  end
  def query
    @id = params["id"]

    if(@id!=nil)
      @alert = Alert.find(@id)
      @AnimalList = AnimalAlert.where(alert_id: @id)
      @UserList = UserAlert.where(alert_id: @id)

      #generate the list of animals
      @AnimalNameList = []
      @AnimalList.each do |a|
          @AnimalNameList.push({
            "id" =>  a.animal.id, 
            "name" => a.animal.name,

          })
      end
      #generate the list of users
      @assigned = false;
      @UserNameList = []
      @UserList.each do |a|
          if(a.user_id == current_user.id)
            @assigned = true;
          end
          @UserNameList.push({
            "id" =>  a.user.id, 
            "name" => a.user.name,

          })
      end
      #generate the json to be returned
      @str = {
        "id" => @alert.id, 
        "title" => @alert.title, 
        "description" => @alert.description,
        "date" => date_format(@alert.date),
        "created_by" =>  [{"name" => @alert.created_by.name, "id" => @alert.created_by.id}], 
        "location" =>  @alert.location,
        "animals" => @AnimalNameList,
        "users" => @UserNameList,
        "user_id" => current_user.id,
        "assigned" => @assigned
      } 



    else
      @alerts = Alert.all
      @str = []
      if (!@alerts.nil?) 
      @alerts.each do |a|
        @str.push({
          "id" =>  a.id, 
          "title" => a.title,
          "description" => a.description,
          "date" => date_format(a.date),

        })
      end
    end



    end
    
    render json: @str
  end
  def update_referer(previous, current)
      if(current!=previous)
        session[:prev_url] = previous.to_s
      end
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/completed.html.erb
<h3> Success!

<p>The alert has been marked as complete </p>

<p>You will no longer receive email notifications for this alert </p>

app/views/alerts/edit.html.erb
 <% provide(:title, 'Alert') %>
<h1>Editing Alert</h1>
<style>
.select-item{
  border:solid;
  border-width: 1px;
  padding:3px;
  border-radius:5px;

  margin:4px;

}
.remove-item{
  position: absolute;
  top: 0;
  right: 0;
  cursor: pointer;
}
</style>
<div class="row">
  <div class="col-md-6 col-md-offset-3 edit_alerts">

    <%= form_for(@alert, html: { multipart: true },  url: alerts_path(@alert)) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control required' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.text_field :date, class: 'datepicker required' %>

      <%= f.label :type%>
      <%= f.collection_select(:alert_type_id, @types, :id, :name, {:prompt => "Select type"}, {class: "required"})%>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>


      <%= label :post, "Assignees" %>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Select Assignee
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <% @users.each do |b| %>
                  <li  class = "assignee-dd-item" id = "assignee-dd-<%= b.id %>"><a href="#" class= "assignee-dd-item" value = '<%= b.id %>'> <%= b.name %></a>  </li> 
                  <% end %>
                </ul>
              </div>             
              <div id = "assignee-list">
        <% @assigneesSelected.each do |b| %>
        <div id = 'assignee-<%= b.id %>'   class = 'select-item assignee-item' style = 'position: relative; display: inline-block;'>
          <p style = 'margin:0px; padding-right:15px'> <%= b.name %> </p> 
          <span class = 'glyphicon glyphicon-remove remove-item remove-assignee' style='margin:2px; float:right;'></span>
        </div>

        <% end %>
      </div>

      <%= text_field_tag 'assignees', "", class: "hidden-assignee", style: "display:none;"  %>

      <!-- sdfasdfasdf -->

      <%= label :post, "Animals" %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Select Animals
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% @animals.each do |b| %>
            <li  class = "animal-dd-item" id = "animal-dd-<%= b.id %>"><a href="#" class= "animal-dd-item" value = '<%= b.id %>'> <%= b.name %></a>  </li> 
            <% end %>
          </ul>
        </div>  
         <div id = "animal-list">
        <% @animalsSelected.each do |b| %>
        <div id = 'animal-<%= b.id %>'   class = 'select-item animal-item' style = 'position: relative; display: inline-block;'>
          <p style = 'margin:0px; padding-right:15px'> <%= b.name %> </p> 
          <span class = 'glyphicon glyphicon-remove remove-item remove-animal' style='margin:2px; float:right;'></span>
        </div>

        <% end %>
      </div>

      <%= text_field_tag 'animals', "", class: "hidden-animal", style: "display:none;"  %>




      <%= f.submit "Create Alert",  class: "btn btn-primary submit-btn" %>
      <button  class= "btn btn-danger alert-delete" id= "delete-<%= @alert.id.to_s %> " > Delete Alert </button>
    <% end %>
    </div>
</div>




</div> <!-- If this is not there there is a line across the screen. Not sure why - J -->
<script>

  $('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".edit_alerts")[0]))
            e.preventDefault()
        
})
  $('.datepicker').datetimepicker({
    //endDate: '+5y',
    format:'YYYY/MM/DD hh:mm A',
    
  });



$(".assignee-selecter").on("change", function(){
    var text = $(".assignee-selecter option:selected").text();
    var val = $(".assignee-selecter option:selected").val();
    if(text == "Select Assignee"){
      return
    }
    html = $("#assignee-list").html();
    html += "<div id = 'assignee-" + val + "'' class = 'assignee-item select-item' style = 'position: relative; display: inline-block;'>" 
        + "<p style = 'margin:0px; padding-right:15px'>" + text + "</p>" + 
       "<span class = 'glyphicon glyphicon-remove remove-assignee remove-item' style='margin:2px; float:right;'>" +"</span>" + 
       " </div>"
    $("#assignee-list").html(html);
    $(".remove-assignee").on("click", function(){
      $(this).closest(".assignee-item").detach()
      setHiddenAssignee();
    })
    //just for now while im setting up the new breeds
    $(this).get(0).selectedIndex = 0;
    setHiddenAssignee();
  })
   $(".assignee-dd-item").on("click", function(e){
    
    e.stopPropagation();
    e.preventDefault();
    var text = $(this).text();
    var val = $(this).attr("value");
    if(text == "Select Assignee"){
      return
    }
    html = $("#assignee-list").html();
    html += "<div id = 'assignee-" + val + "'' class = 'assignee-item select-item' style = 'position: relative; display: inline-block;'>" 
        + "<p style = 'margin:0px; padding-right:15px'>" + text + "</p>" + 
       "<span class = 'glyphicon glyphicon-remove remove-assignee remove-item' style='margin:2px; float:right;'>" +"</span>" + 
       " </div>"
    $("#assignee-list").html(html);
    $(".remove-assignee").on("click", function(){
      $(this).closest(".assignee-item").detach()
      setHiddenAssignee();
    })
    //just for now while im setting up the new breeds
    $(this).get(0).selectedIndex = 0;
    setHiddenAssignee();
  })
  function setHiddenAssignee(){
    str = ""
    $(".assignee-dd-item").show();
    $(".assignee-item").each(function(){
      var id = this.id.split("-")[1]
      $("#assignee-dd-" +id).hide();
      str += id + "|"
    })
    $(".hidden-assignee").val(str)
  }

  $(".remove-assignee").on("click", function(){
      $(this).closest(".assignee-item").detach()
      setHiddenAssignee();
  })





  setHiddenAssignee();
  

$(".animal-dd-item").on("click", function(e){

    e.stopPropagation();
    e.preventDefault();
    var text = $(this).text();
    var val = $(this).attr("value");
    if(text == "Select Animal"){
      return
    }
    html = $("#animal-list").html();
    html += "<div id = 'animal-" + val + "'' class = 'animal-item select-item' style = 'position: relative; display: inline-block;'>" 
        + "<p style = 'margin:0px; padding-right:15px'>" + text + "</p>" + 
       "<span class = 'glyphicon glyphicon-remove remove-animal remove-item' style='margin:2px; float:right;'>" +"</span>" + 
       " </div>"
    $("#animal-list").html(html);
    $(".remove-animal").on("click", function(){
      $(this).closest(".animal-item").detach()
      setHiddenAnimal();
    })
    //just for now while im setting up the new breeds
    $(this).get(0).selectedIndex = 0;
    setHiddenAnimal();
  })

   function setHiddenAnimal(){
    str = ""
    $(".animal-dd-item").show();

    $(".animal-item").each(function(){
      var id = this.id.split("-")[1]
      $("#animal-dd-" +id).hide();
      str += id + "|"
    })
    $(".hidden-animal").val(str)
  }

  setHiddenAnimal();
  $(".remove-animal").on("click", function(){
      $(this).closest(".animal-item").detach()
      setHiddenAnimal();
  })
$(".alert-delete").on("click", function(event){
  event.preventDefault()
  $.ajax({
    type: "DELETE",
    url: "/alerts",
    data: "param=" + $(this).attr("id").split("-")[1],
    success: function(msg){
        window.location = "<%= session[:prev_url] %>"
    },
    error: function(e){
      alert("unable to delete alert")

    }
  });
});

</script>

app/views/alerts/new.html.erb
 <% provide(:title, 'Alert') %>
<h1>Add new alert</h1>
<style>
.select-item{
  border:solid;
  border-width: 1px;
  padding:3px;
  border-radius:5px;

  margin:4px;

}
.remove-item{
  position: absolute;
  top: 0;
  right: 0;
  cursor: pointer;
}
</style>
<div class="row">
  <div class="col-md-6 col-md-offset-3 new_alerts">

    <%= form_for(@alert, html: { multipart: true },  url: alerts_path(@alert)) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control required'  %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.text_field :date, class: 'datepicker required' %>

      <%= f.label :type%>
      <%= f.collection_select(:alert_type_id, @types, :id, :name, {:prompt => "Select type"}, {class: "required"})%>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control ' %>


      <%= label :post, "Assignees" %>
      <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Select Assignee
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <% @users.each do |b| %>
                  <li  class = "assignee-dd-item" id = "assignee-dd-<%= b.id %>"><a href="#" class= "assignee-dd-item" value = '<%= b.id %>'> <%= b.name %></a>  </li> 
                  <% end %>
                </ul>
              </div>           



      <div id = "assignee-list"></div>

      <%= text_field_tag 'assignees', "", class: "hidden-assignee", style: "display:none;"  %>



      <%= label :post, "Animals" %>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Select Animals
          <span class="caret"></span></button>
          <ul class="dropdown-menu">
            <% @animals.each do |b| %>
            <li  class = "animal-dd-item" id = "animal-dd-<%= b.id %>"><a href="#" class= "animal-dd-item" value = '<%= b.id %>'> <%= b.name %></a>  </li> 
            <% end %>
          </ul>
        </div>   

           <div id = "animal-list">
        <% @animal.each do |b| %>
        <div id = 'animal-<%= b.id %>'   class = 'select-item animal-item' style = 'position: relative; display: inline-block;'>
          <p style = 'margin:0px; padding-right:15px'> <%= b.name %> </p> 
          <span class = 'glyphicon glyphicon-remove remove-item remove-animal' style='margin:2px; float:right;'></span>
        </div>

        <% end %>
      </div>

      <%= text_field_tag 'animals', "", class: "hidden-animal", style: "display:none;"  %>



      <br>
      <%= f.label :required , "Spayed/Neutered" do %>
        <p style = "display: inline-block">Completion Required</p>
        <%= f.check_box :required, {style: "display: inline-block; width:auto;"} %>
                 
      <% end %>
      <%= f.submit "Create Alert", class: "btn btn-primary submit-btn" %>
    <% end %>
    </div>
</div>




</div> <!-- If this is not there there is a line across the screen. Not sure why - J -->
<script>
  $('.submit-btn').on('click', function(e){
        if (!validateForm($(this).closest(".new_alerts")[0]))
            e.preventDefault()
        
  })
 
  $('.datepicker').datetimepicker({
    //endDate: '+5y',
    format:'YYYY/MM/DD hh:mm A',
    
  });



  $(".assignee-dd-item").on("click", function(e){
    
    e.stopPropagation();
    e.preventDefault();
    var text = $(this).text();
    var val = $(this).attr("value");
    if(text == "Select Assignee"){
      return
    }
    html = $("#assignee-list").html();
    html += "<div id = 'assignee-" + val + "'' class = 'assignee-item select-item' style = 'position: relative; display: inline-block;'>" 
        + "<p style = 'margin:0px; padding-right:15px'>" + text + "</p>" + 
       "<span class = 'glyphicon glyphicon-remove remove-assignee remove-item' style='margin:2px; float:right;'>" +"</span>" + 
       " </div>"
    $("#assignee-list").html(html);
    $(".remove-assignee").on("click", function(){
      $(this).closest(".assignee-item").detach()
      setHiddenAssignee();
    })
    //just for now while im setting up the new breeds
    $(this).get(0).selectedIndex = 0;
    setHiddenAssignee();
  })
  function setHiddenAssignee(){
    str = ""
    $(".assignee-dd-item").show();
    $(".assignee-item").each(function(){
      var id = this.id.split("-")[1]
      $("#assignee-dd-" +id).hide();
      str += id + "|"
    })
    $(".hidden-assignee").val(str)
  }




$(".animal-dd-item").on("click", function(e){

    e.stopPropagation();
    e.preventDefault();
    var text = $(this).text();
    var val = $(this).attr("value");
    if(text == "Select Animal"){
      return
    }
    html = $("#animal-list").html();
    html += "<div id = 'animal-" + val + "'' class = 'animal-item select-item' style = 'position: relative; display: inline-block;'>" 
        + "<p style = 'margin:0px; padding-right:15px'>" + text + "</p>" + 
       "<span class = 'glyphicon glyphicon-remove remove-animal remove-item' style='margin:2px; float:right;'>" +"</span>" + 
       " </div>"
    $("#animal-list").html(html);
    $(".remove-animal").on("click", function(){
      $(this).closest(".animal-item").detach()
      setHiddenAnimal();
    })
    //just for now while im setting up the new breeds
    $(this).get(0).selectedIndex = 0;
    setHiddenAnimal();
  })
  function setHiddenAnimal(){
    str = ""
    $(".animal-dd-item").show();

    $(".animal-item").each(function(){
      var id = this.id.split("-")[1]
      $("#animal-dd-" +id).hide();
      str += id + "|"
    })
    $(".hidden-animal").val(str)
  }

setHiddenAnimal();
  $(".remove-animal").on("click", function(){
      $(this).closest(".animal-item").detach()
      setHiddenAnimal();
  })

</script>